---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
requirements:
  requiredStorage: 32
  requiredRam: 2.0
  check:
    - storage
    - ram
    - root
  required:
    - storage
    - ram
    - root

