import { toolRegistry } from './registry';
import { ToolDefinition } from './types';

export const verifiedToolDefinitions: ToolDefinition[] = [
  {
    toolId: 'runtime.get_status',
    name: 'Get Runtime Status',
    description: 'Queries Kingdom runtime engine state, scheduler status, version, and task counters.',
    version: '1.0.0',
    capabilities: ['runtime.status', 'node.execute'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'runtime.start',
    name: 'Start Engine',
    description: 'Starts the Kingdom runtime engine and task scheduler.',
    version: '1.0.0',
    capabilities: ['runtime.start'],
    category: 'MUTATING',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'MEDIUM',
    requiresApproval: false,
    timeoutMs: 10000,
    sideEffects: true,
  },
  {
    toolId: 'runtime.stop',
    name: 'Stop Engine',
    description: 'Gracefully stops the Kingdom runtime engine.',
    version: '1.0.0',
    capabilities: ['runtime.stop'],
    category: 'MUTATING',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'HIGH',
    requiresApproval: false,
    timeoutMs: 10000,
    sideEffects: true,
  },
  {
    toolId: 'runtime.get_mode',
    name: 'Get Mode',
    description: 'Queries the current operating mode of the Kingdom engine.',
    version: '1.0.0',
    capabilities: ['runtime.mode.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'runtime.set_mode',
    name: 'Set Operating Mode',
    description: 'Updates the active operating mode of Kingdom engine (adaptive or lightweight).',
    version: '1.0.0',
    capabilities: ['runtime.mode.write'],
    category: 'MUTATING',
    inputSchema: {
      type: 'object',
      properties: {
        mode: { type: 'string', description: 'Mode name (adaptive or lightweight)', required: true, enum: ['adaptive', 'lightweight'] },
      },
      required: ['mode'],
    },
    riskClass: 'MEDIUM',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: true,
  },
  {
    toolId: 'tasks.submit',
    name: 'Submit Task Prompt',
    description: 'Submits a prompt task to the Kingdom swarm for execution.',
    version: '1.0.0',
    capabilities: ['tasks.create'],
    category: 'MUTATING',
    inputSchema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', description: 'Prompt text payload', required: true },
      },
      required: ['prompt'],
    },
    riskClass: 'MEDIUM',
    requiresApproval: false,
    timeoutMs: 10000,
    sideEffects: true,
  },
  {
    toolId: 'tasks.list',
    name: 'List Tasks',
    description: 'Lists active and historical Kingdom swarm tasks.',
    version: '1.0.0',
    capabilities: ['tasks.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'tasks.get',
    name: 'Get Task Details',
    description: 'Retrieves details for a specific task ID.',
    version: '1.0.0',
    capabilities: ['tasks.read'],
    category: 'READ_ONLY',
    inputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string', description: 'Task UUID', required: true },
      },
      required: ['taskId'],
    },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'tasks.cancel',
    name: 'Cancel Task',
    description: 'Requests cancellation of a queued or running Kingdom task.',
    version: '1.0.0',
    capabilities: ['tasks.cancel'],
    category: 'MUTATING',
    inputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string', description: 'Task UUID to cancel', required: true },
      },
      required: ['taskId'],
    },
    riskClass: 'HIGH',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: true,
  },
  {
    toolId: 'knights.list',
    name: 'List Swarm Knights',
    description: 'Queries active swarm knights and workload counters.',
    version: '1.0.0',
    capabilities: ['knights.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'models.health',
    name: 'Query Models Health',
    description: 'Inspects health and status of AI model providers.',
    version: '1.0.0',
    capabilities: ['models.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'memory.read',
    name: 'Get Memory Entries',
    description: 'Retrieves recorded memory entries.',
    version: '1.0.0',
    capabilities: ['memory.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'memory.search',
    name: 'Search Memory',
    description: 'Performs vector search across Kingdom memory graph.',
    version: '1.0.0',
    capabilities: ['memory.search'],
    category: 'READ_ONLY',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search query string', required: true },
      },
      required: ['query'],
    },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'maps.list',
    name: 'List Intelligence Maps',
    description: 'Lists saved AI intelligence graph maps.',
    version: '1.0.0',
    capabilities: ['ai_map.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'security.status',
    name: 'Get Security Health',
    description: 'Retrieves ZeroTrust security health and pending approval counts.',
    version: '1.0.0',
    capabilities: ['security.status.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'security.permissions',
    name: 'List Node Permissions',
    description: 'Queries registered node capability bindings.',
    version: '1.0.0',
    capabilities: ['security.permissions.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'security.approvals_list',
    name: 'List Approval Requests',
    description: 'Lists pending and historical security approval requests.',
    version: '1.0.0',
    capabilities: ['security.approvals.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: {}, required: [] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'security.approval_create',
    name: 'Create Approval Request',
    description: 'Creates a security approval request for restricted actions.',
    version: '1.0.0',
    capabilities: ['security.approvals.create'],
    category: 'MUTATING',
    inputSchema: {
      type: 'object',
      properties: {
        capability: { type: 'string', description: 'Requested capability', required: true },
        operation: { type: 'string', description: 'Operation description', required: true },
      },
      required: ['capability', 'operation'],
    },
    riskClass: 'HIGH',
    requiresApproval: true,
    timeoutMs: 5000,
    sideEffects: true,
  },
  {
    toolId: 'filesystem.read',
    name: 'Filesystem Read',
    description: 'Reads file content in local sandbox',
    version: '1.0.0',
    capabilities: ['filesystem.read'],
    category: 'READ_ONLY',
    inputSchema: { type: 'object', properties: { path: { type: 'string', description: 'Target file path' } }, required: ['path'] },
    riskClass: 'LOW',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: false,
  },
  {
    toolId: 'filesystem.write',
    name: 'Filesystem Write',
    description: 'Writes file content in local sandbox',
    version: '1.0.0',
    capabilities: ['filesystem.write'],
    category: 'MUTATING',
    inputSchema: { type: 'object', properties: { path: { type: 'string', description: 'Target file path' } }, required: ['path'] },
    riskClass: 'MEDIUM',
    requiresApproval: false,
    timeoutMs: 5000,
    sideEffects: true,
  },
  {
    toolId: 'filesystem.delete_restricted',
    name: 'Restricted Filesystem Delete',
    description: 'Privileged filesystem deletion capability (Requires human approval).',
    version: '1.0.0',
    capabilities: ['filesystem.delete'],
    category: 'PRIVILEGED',
    inputSchema: {
      type: 'object',
      properties: {
        target: { type: 'string', description: 'Target file or directory path', required: true },
      },
      required: ['target'],
    },
    riskClass: 'CRITICAL',
    requiresApproval: true,
    timeoutMs: 10000,
    sideEffects: true,
  },
  {
    toolId: 'process.execute_restricted',
    name: 'Restricted Process Execution',
    description: 'Privileged process execution capability (Requires human approval).',
    version: '1.0.0',
    capabilities: ['process.execute'],
    category: 'PRIVILEGED',
    inputSchema: {
      type: 'object',
      properties: {
        command: { type: 'string', description: 'Command string', required: true },
      },
      required: ['command'],
    },
    riskClass: 'CRITICAL',
    requiresApproval: true,
    timeoutMs: 10000,
    sideEffects: true,
  },
];

export function initializeVerifiedTools(): void {
  for (const tool of verifiedToolDefinitions) {
    try {
      toolRegistry.register(tool);
    } catch (e) {
      // Already registered
    }
  }
  toolRegistry.lockRegistry();
}

initializeVerifiedTools();
